name: Python script unit and integeration tests
on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  lint:
    runs-on:  ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.7'
          architecture: 'x64'
      - name: Install dependencies
        run: pip install -r requirements_dev.txt; pip install -r requirements.txt
        shell: bash
      - name: Run python unit tests
        run: python -m unittest discover -p "*_test.py"
