name: Test action
on:
  pull_request:
    branches:
      - develop

jobs:
  send_notifications:
    name: Send pending review notifications in test mode
    runs-on:  ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.7'
          architecture: 'x64'