name: Test action
on:
  pull_request:
    branches:
      - master

jobs:
  send_notifications:
    name: Send pending review notifications in test mode
    runs-on:  ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.7'
          architecture: 'x64'
      - uses: DubeySandeep/pending-review-notification@init
        with:
          team-slug: test-team
          # GITHUB_TOKEN does not have rights to send notification, this is used
          # as a placeholder here as the action is running in test node.
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          review-turnaround-hours: 0
          test-mode: True
        env:
          TEST_MODE_ENV: ${{ true }}